// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9MIWyBoQqQ6QfKfNw0FlabIsyA-R5Ht4',
    appId: '1:615639053371:web:933a88e007513dbebc181e',
    messagingSenderId: '615639053371',
    projectId: 'catatkelas',
    authDomain: 'catatkelas.firebaseapp.com',
    storageBucket: 'catatkelas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDGZ0R_eks-XlitpmZwFGPVc6BuNY6Tk',
    appId: '1:615639053371:android:7f8a7b47139f16d3bc181e',
    messagingSenderId: '615639053371',
    projectId: 'catatkelas',
    storageBucket: 'catatkelas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3VH6vkRGHtl_wSjtsRZ7MQxqI913pqes',
    appId: '1:615639053371:ios:c9fbdf7f6bde4b66bc181e',
    messagingSenderId: '615639053371',
    projectId: 'catatkelas',
    storageBucket: 'catatkelas.firebasestorage.app',
    iosBundleId: 'com.example.catatKelas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3VH6vkRGHtl_wSjtsRZ7MQxqI913pqes',
    appId: '1:615639053371:ios:c9fbdf7f6bde4b66bc181e',
    messagingSenderId: '615639053371',
    projectId: 'catatkelas',
    storageBucket: 'catatkelas.firebasestorage.app',
    iosBundleId: 'com.example.catatKelas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9MIWyBoQqQ6QfKfNw0FlabIsyA-R5Ht4',
    appId: '1:615639053371:web:76cfe28dbd5497e8bc181e',
    messagingSenderId: '615639053371',
    projectId: 'catatkelas',
    authDomain: 'catatkelas.firebaseapp.com',
    storageBucket: 'catatkelas.firebasestorage.app',
  );
}
